name: git-clone pull request pipelines
on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    types:
    - opened
    - reopened
    - unlocked
    - edited
    branches:
    - 'feature/**'

jobs:

  cargo-test:
    name: Cargo tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: cargo test --verbose

  cli-test:
    name: Functional tests
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          macos-latest,
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Prep
        run: |
          cargo build --release
          temp=$(mktemp -d)
          git config --local 'tanjarinne.git-clone.root-path' $temp
